Feature/display errors
peseb/turplanleggerwebui pull request #23
Opened 2023-03-14 17:50 UTC by peseb

Display error if api-request returns errorresponse

2023-03-14 18:00 UTC, sixcare requested changes
`:`

2023-03-14 18:02 UTC, peseb commented on public/locales/en/translation.json
> +    "title": "Woops, something went wrong:"
Done:)

2023-03-14 18:02 UTC, peseb commented on public/locales/no/translation.json
> +    "title": "Oida, noe gikk galt:"
Done:)

2023-03-16 17:09 UTC, sixcare approved these changes

2023-03-16 17:38 UTC, merged